/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as alphaPingSol from "./AlphaPING.sol";
export type { alphaPingSol };
export type { ERC20Faucet } from "./ERC20Faucet";
