/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AlphaPING__factory } from "./AlphaPING__factory";
export { IERC20__factory } from "./IERC20__factory";
