export const defaultTokenMetadata: tokenMetadata = {
    id: 0,
    name: '',
    category: '',
    description: '',
    contract_address: [],
    date_added: '',
    date_launched: '',
    infinite_supply: false,
    is_hidden: 0,
    logo: '',
    notice: '',
    platform: {
      id: '',
      name: '',
      slug: '',
      symbol: '',
      token_address: '',
    },
    self_reported_market_circulating_supply: '',
    self_reported_market_cap: '',
    self_reported_tags: '',
    slug: '',
    subreddit: '',
    symbol: '',
    "tag-groups": [],
    "tag-names": [],
    tags: [],
    twitter_username: [],
    urls: {
        announcement: [],
        chat: [],
        explorer: [],
        facebook: [],
        message_board: [],
        reddit: [],
        source_code: [],
        technical_doc: [],
        twitter: [],
        website: [],
    }
}